Getting error code AttributeError: Got AttributeError when attempting to get a value for field  on serializer . The serializer field might be named incorrectly and not match any attribute or key on the  instance. Original exception text was: 'QuerySet' object has no attribute 'first_name'..  Will continue to look into the root cause of this error